### ISSUE TITLE
Cannot find login form..

### ISSUE THREAD

**Issue by INFOBA** [Arachni/arachni#938]
So .. Arachni cannot find my login form - do you have any ideas?

I've tried with these parameters:
Username
Password

and

ctl00_bodyArea_Login1_UserName
ctl00_bodyArea_Login1_Password

----

plugins:
  autologin:
    url: https://beta.infoba.dk/login.aspx?ReturnUrl=%2fIN%2f
    parameters: Username=ArachniIN&Password=********
[arachniin.txt](https://github.com/Arachni/arachni/files/1572288/arachniin.txt)

    check: https://beta.infoba.dk/IN/
  autothrottle: 
  discovery: 
  healthmap: 
  timing_attacks: 
  uniformity: 
no_fingerprinting: false
authorized_by: 
url: https://beta.infoba.dk/IN/
--------------------------------------------------------------------------------
[2017-12-19 17:01:39 +0100] [Arachni::Session::Error::FormNotFound] Login form could not be found with: {:url=>"https://beta.infoba.dk/login.aspx?ReturnUrl=%2fIN%2f", :inputs=>{"Username"=>"ArachniIN", "Password"=>"********"}}

**Comment by Zapotek** [comment]
`ctl00_bodyArea_Login1_UserName` and `ctl00_bodyArea_Login1_Password` are IDs, try using their names:

* `ctl00$bodyArea$Login1$UserName`
* `ctl00$bodyArea$Login1$Password`

**Comment by INFOBA** [comment]
Hi Zapotek. 

Thanks for your response.

Okay, so now it found the login form I guess.

However, Arachni does not login.
Backend I have a system logging who logs in, and the user ArachniIN has not logged in. 

What can I do to help you, help me?

plugins:
  autologin:
    url: https://beta.infoba.dk/login.aspx
    parameters: ctl00$bodyArea$Login1$UserName=ArachniIN&ctl00$bodyArea$Login1$Password=********
    check: https://beta.infoba.dk/IN/
no_fingerprinting: false
authorized_by: 
url: https://beta.infoba.dk/IN/
--------------------------------------------------------------------------------
[2017-12-20 08:46:52 +0100] The response did not match the verifier.

**Comment by Zapotek** [comment]
The `check` option sets a string to be found in the response, not a URL, in case you're confused.
If not, are you sure that `https://beta.infoba.dk/IN/` is a good check? I looked at the HTML of that website and all links are relative, what you've set probably won't match anything.

You may also need more specialized check options, but let's take it one step at a time.

**Comment by INFOBA** [comment]
Hi again.

Okay, so what I did:

1. Go to beta.infoba.dk 
2. Hit F12 in Chrome
3. Click "Log ind" > (https://beta.infoba.dk/login.aspx)
4. Log in
5. In the F12 in Chrome, choose "Network"
6. I pick the one of the "logs" with something in "Response"
7. Then I pick a random string which is only there, when the user is logged in: INFOBA - Institution (I also tried with "Log ud")

Result: The response did not match the verifier.

![image](https://user-images.githubusercontent.com/25983267/34247282-352748ea-e632-11e7-87a9-7852bd766306.png)

**Comment by INFOBA** [comment]
Hi! This is still a problem for me.

**Comment by wanglei409** [comment]
Is this problem solved now？？？？？

**Comment by INFOBA** [comment]
Zapotek Hi @wanglei409 - still a problem. Haven't heard anything from @Zapotek
